user_config: # path to config file to update

gpus: 0
hop_length: 1024
n_fft: 4096
sequence_length: 327680
sampling_rate: 44100
min_midi: 21
max_midi: 108
learning_rate: 1e-5
epochs: 1000
download: False
data_root: '/data2/kinwai'

dataset:
    train:
        root: ${data_root} 
        groups: 'train'
        data_type: 'MUS'
        download: ${download}
        preload: False
        sequence_length: ${sequence_length}
        seed: 42
        hop_length: ${hop_length}
        max_midi: 108
        min_midi: 21
        ext_audio: '.wav'
        sampling_rate: ${sampling_rate}
        overlap: False
        mfm_path: '/data2/kinwai/mfm_features_top_koyama/'
    test:
        root: ${data_root} 
        groups: 'test'
        data_type: 'MUS'
        download: False
        preload: False
        sequence_length: ${sequence_length}
        seed: 42
        hop_length: ${hop_length}
        max_midi: 108
        min_midi: 21
        ext_audio: '.wav'
        sampling_rate: ${sampling_rate}
        mfm_path: '/data2/kinwai/mfm_features_top_koyama/'        
        overlap: True
        
dataloader:
    train:
        batch_size: 16
        num_workers: 8
        shuffle: True
        pin_memory: True
    valid:
        batch_size: 16
        num_workers: 8
        shuffle: False
        pin_memory: True
    test:
        batch_size: 4
        num_workers: 8
        shuffle: False
        pin_memory: True

pl:
    lr: ${learning_rate}
    sr: ${sampling_rate}
    hop_length: ${hop_length}
    min_midi: ${min_midi}

defaults:    
    - spec_layer: Mel
    - model: Attention_CNN
        
        
        
        
        
