user_config: # path to config file to update

gpus: 1
hop_length: 512
sequence_length: 327680
sampling_rate: 44100
min_midi: 21
max_midi: 108
learning_rate: 1e-5
epochs: 1000
download: False
data_root: '/workspace/public_data/MusicDataset'
        
dataloader:
    train:
        batch_size: 16
        num_workers: 8
        shuffle: True
        pin_memory: True
    valid:
        batch_size: 16
        num_workers: 8
        shuffle: False
        pin_memory: True
    test:
        batch_size: 4
        num_workers: 8
        shuffle: False
        pin_memory: True

pl:
    lr: ${learning_rate}
    sr: ${sampling_rate}
    hop_length: ${hop_length}
    min_midi: ${min_midi}

defaults:    
    - spec_layer: Mel
    - dataset: MAPS
    - model: Attention_CNN
        
        
        
        
        
