batch_size: 4
sr: 16000

dataset:                         
    train:
      root: "train"
      sr: ${sr}
    test:
      root: "train"
      batch_size: 
      sr: ${sr}
      
model:
    arg1:
        a: 1
        b: 2
        c: 3
    arg2:
        sr: ${sr}