gpus: 1
hop_length: 160
sampling_rate: 16000
learning_rate: 1e-5
epochs: 400
output_mode: 'ph'
download: False
val_frequency: 1
data_root: './SpeechDataset'

dataset:
    train:
        root: ${data_root}
        split: 'train'
        download: ${download}
        
        
    test:
        root: ${data_root}
        split: 'test'
        download: False
        
dataloader:
    train:
        batch_size: 16
        num_workers: 8
        pin_memory: True
        
    valid:
        batch_size: 32
        num_workers: 8
        pin_memory: True
        
    test:
        batch_size: 1
        num_workers: 8
        pin_memory: True
        
data_processing:
    input_key: 'waveform'
    label_key: 0 # will be overwritten inside the code
    downsample_factor: ${hop_length}
    
    
model_checkpoint:
    monitor: "valid_ctc_loss"
    filename: "{epoch:02d}-{valid_ctc_loss:.2f}-{valid_PER:.2f}"
    save_top_k: 1
    save_last: True
    mode: "min"
    
trainer:
    gpus: ${gpus}
    max_epochs: ${epochs}
    accelerator: 'ddp'
    sync_batchnorm: True
    replace_sampler_ddp: False
    profiler: 'simple'
    check_val_every_n_epoch: ${val_frequency}
    num_sanity_val_steps: 2
    resume_from_checkpoint: 'outputs/2022-02-18/18-03-51/ASR-MelSpectrogram-simpleLSTM/version_1/checkpoints/epoch=17-valid_ctc_loss=3.36-PER=0.00.ckpt'    

pl: 
    lr: ${learning_rate}  
    
defaults:    
    - spec_layer: Mel
    - model: simpleLSTM