user_config: # path to config file to update

gpus: 1
hop_length: 160
sampling_rate: 16000
learning_rate: 1e-5
epochs: 400
output_mode: 'ph'

dataset:
    train:
        root: '/workspace/public_data/SpeechDataset'
        split: 'train'
        download: True
        
        
    test:
        root: '/workspace/public_data/SpeechDataset'
        split: 'test'
        download: False
        
dataloader:
    train:
        batch_size: 16
        num_workers: 8
        pin_memory: True
        
    valid:
        batch_size: 32
        num_workers: 8
        pin_memory: True
        
    test:
        batch_size: 1
        num_workers: 8
        pin_memory: True
        
data_processing:
    input_key: 'waveform'
    label_key: 0 # will be overwritten inside the code
    downsample_factor: ${hop_length}
        
pl: 
    lr: ${learning_rate}  
    
defaults:    
    - spec_layer: Mel
    - model: simpleLSTM