user_config: # path to config file to update

gpus: 1
hop_length: 160
sampling_rate: 16000
learning_rate: 1e-4
epochs: 400
output_mode: 'ph'
download: False
  
dataloader:
    train:
        batch_size: 16
        num_workers: 8
        pin_memory: True
        
    valid:
        batch_size: 32
        num_workers: 8
        pin_memory: True
        
    test:
        batch_size: 1
        num_workers: 8
        pin_memory: True
        
pl: 
    lr: ${learning_rate}  
    
defaults:    
    - spec_layer: Mel
    - dataset: SpeechCommand
    - model: simpleLinear_flatten