name: MusicNet
train:
    root: ${data_root} 
    groups: 'train'
    download: ${download}
    preload: False
    sequence_length: ${sequence_length}
    seed: 42
    hop_length: ${hop_length}
    max_midi: 108
    min_midi: 21
    ext_audio: '.wav'
    sampling_rate: ${sampling_rate}
test:
    root: ${data_root} 
    groups: 'test'
    download: ${download}
    preload: False
    sequence_length: ${sequence_length}
    seed: 42
    hop_length: ${hop_length}
    max_midi: 108
    min_midi: 21
    ext_audio: '.wav'
    sampling_rate: ${sampling_rate}