user_config: # path to config file to update

gpus: 1
hop_length: 160
sampling_rate: 16000
learning_rate: 1e-5
epochs: 400

dataset:
    train:
        root: '/workspace/public_data/SpeechDataset'
        split: 'train'
        download: False
        
        
    valid:
        root: '/workspace/public_data/SpeechDataset'
        split: 'test'
        download: False
        
dataloader:
    train:
        batch_size: 16
        num_workers: 8
        pin_memory: True
        
    valid:
        batch_size: 32
        num_workers: 8
        pin_memory: True
        
data_processing:
    input_key: 'waveform'
    label_key: 'phonemics'
    downsample_factor: ${hop_length}
        
model:
    lr: ${learning_rate}  
    
    
spec_layer:
    sr: ${sampling_rate}
    n_fft: 400
    n_mels: 80
    hop_length: ${hop_length}
    window: 'hann'
    center: True
    pad_mode: 'reflect'
    power: 2.0
    htk: False
    fmin: 0.0
    fmax: null
    norm: 1
    trainable_mel: False
    trainable_STFT: False
    verbose: True