type: 'Attention_CNN'
args:
    norm_mode: 'imagewise'
    hidden_dim: 768
    output_dim: 88 # piano has 88 notes
    onset: False
    input_dim: ${spec_layer.args.n_mels} # it is the number of mel bins/spec bands